name: SpawnStar
main: com.winterhavenmc.spawnstar.PluginMain
author: ${project.author}
version: ${project.version}
api-version: 1.16
softdepend: [ Multiverse-Core ]

commands:
  spawnstar:
    description: This is the SpawnStar command.
    usage: /spawnstar [command]

permissions:
  spawnstar.use:
    description: Allows the use of a spawnstar.
    default: true

  spawnstar.status:
    description: Allows display of config settings.
    default: op

  spawnstar.reload:
    description: Allows reloading the config file.
    default: op

  spawnstar.give:
    description: Allows giving SpawnStar items to players.
    default: op

  spawnstar.destroy:
    description: Allows destroying SpawnStar items in hand.
    default: op

  spawnstar.admin:
    description: Allows all admin commands
    default: op
    children:
      spawnstar.status: true
      spawnstar.reload: true
      spawnstar.give: true
      spawnstar.destroy: true
      